### PR TITLE
Move service class to correct package

### LINKED ISSUE #312: Service classes in wrong package
**Describe the bug**
While working on #311 I noticed that the service classes are placed in the wrong package. Instead of adding them to the `service` package, they are added to `service.impl`.

**To Reproduce**
Generate an application that uses service classes. It doesn't matter if the service classes are created because of the `dto` or `service` option. 
```
application {
  config {
    prodDatabaseType postgresql
  }

  entities *
}

entity Category {
  description String required
}
entity Post {
  title String required
}
service Category with serviceClass
dto Post with mapstruct
```

**Expected behavior**
The service classes are in the `service` package and not in `impl`. All the imports expect the service classes to be in `service`, and also the base JHipster generator does not use an `impl` package like that.

### PR DESCRIPTION
**Pull request by emilpaw**
Fixes #312

### CODE REVIEW

File: generators/quarkus/entity-files.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ export const entityQuarkusFiles = {
         }),
         javaMainPackageTemplatesBlock({
             condition: generator => generator.service === 'serviceClass' && !generator.embedded,
-            renameTo: (data, filename) => filename.replace('ServiceImpl.java', 'Service.java'),
+            renameTo: (_data, file) => file.replace('service/impl', 'service').replace('Impl.java', '.java'),
             templates: ['_entityPackage_/service/impl/_entityClass_ServiceImpl.java'],
```
Comment (mraible) [inline generators/quarkus/entity-files.js:48]: It seems easier to rename the template. Why not choose that route?

Comment (emilpaw) [reply generators/quarkus/entity-files.js:48]: The same template is used for serviceClass and serviceImpl. So a rename is necessary one way or another.

It's also implemented in the base JHipster like that.
